; WAL — это механизм, с помощью которого PostgreSQL отслеживает все изменения в базе данных и записывает их в журнал.
; Значение 'logical' указывает, что PostgreSQL будет регистрировать изменения на уровне отдельных строк,
; а не на уровне страниц.
wal_level = 'logical'

; определяет максимальное количество процессов, которые могут одновременно читать журнал WAL.
max_wal_senders = 1

; максимальное количество слотов репликации, которые могут быть созданы в базе данных. Слот репликации — это механизм,
; который позволяет процессам читать журнал WAL и передавать изменения в другую базу данных или в Kafka.
max_replication_slots = 1