# REPLICATION / WAL SETTINGS
listen_addresses = '*'
# Разрешаем PostgreSQL принимать подключения не только с localhost, но и с других хостов/контейнеров

wal_level = logical
# Включаем logical replication — это обязательное требование для Debezium и CDC

max_wal_senders = 5
# Максимум процессов, которые могут одновременно передавать WAL подписчикам, репликам или Debezium

max_replication_slots = 5
# Максимум replication slots; slot нужен Debezium, чтобы читать изменения из WAL без потери позиции

max_slot_wal_keep_size = 1GB
# Ограничиваем, сколько WAL может удерживать replication slot, чтобы диск не заполнился при отставании коннектора

wal_keep_size = 512MB
# Держим запас WAL-файлов для репликации, чтобы кратковременный лаг не приводил к потере нужных сегментов

wal_compression = on
# Сжимаем WAL-записи, чтобы уменьшить нагрузку на диск и объем WAL при UPDATE/DELETE


# PERFORMANCE
shared_buffers = 256MB
# Внутренний кэш PostgreSQL для страниц данных; ускоряет чтение часто используемых данных

work_mem = 16MB
# Память на одну операцию сортировки, хеширования или агрегации в запросе; влияет на выполнение SELECT

maintenance_work_mem = 128MB
# Память для служебных операций: VACUUM, CREATE INDEX, ALTER TABLE, autovacuum

checkpoint_timeout = 15min
# Максимальный интервал между checkpoint; влияет на частоту сброса грязных страниц на диск

max_worker_processes = 8
# Лимит фоновых worker-процессов PostgreSQL; нужен для parallel workers, logical replication и служебных задач

# CONNECTIONS
max_connections = 100
# Максимальное количество одновременных клиентских подключений к PostgreSQL